### ISSUE TITLE
Not Recommended?

### ISSUE THREAD

**Issue by mxmissile** [khalidabuhakmeh/MudBlazorInRazor#1]
` I don't recommend this approach` - Is there another better recommendation? I really would like to use MudBlazor styles and themes in my razor pages.

**Comment by khalidabuhakmeh** [comment]
@mxmissile I don't recommend this approach because the components were designed with interactivity in mind. If you want to use the styles and themes, then that use case would be ok, but be aware you'll have to implement those yourself. Cheers :)
